### ISSUE TITLE
nord full theme not working

### ISSUE THREAD

**Issue by Candlemass** [csalmeida/protonmail-themes#60]
Hello,

I'm trying to use the "nord full" theme but not having any luck.

I followed your instructions:

-Installed "stylus" extension for Firefox
-Wrote a new style by copy and pasting your entire "raw" code
-Enabled it for "URLs on the domain" for both "beta.protonmail.com" and "mail.protonmail.com"
-When logged into ProtonMail the "stylus" icon next to the browser URL bar shows a "1" indicating that the style should be enabled
-When logged into ProtonMail "settings>appearance>custom themes" box is completely empty

Nothing has changed.

ProtonMail version prior to logging in indicates "v3.16.51"

Thanks in advance.

**Comment by Candlemass** [comment]
Okay, I just noticed that the "nord" theme is only for beta 4.0+ versions. My mistake.

It seems to be working in beta however I'm trying to use the FULL version of the theme and the code I copy + pasted is only working partially.

Can you please tell me to to activate the "nord FULL" theme?

Thank you.

**Comment by csalmeida** [comment]
Hi @Candlemass,

That's correct, in order to use these themes you have to use the version `4.x.x` of the app. In order to have the theme apply to  more areas of the UI you can toggle dark mode from a dropdown menu in ProtonMail. I have attached a screenshot below, please let me know if this helps.

<img width="283" alt="Screenshot 2021-01-07 at 23 45 33" src="https://user-images.githubusercontent.com/12223613/103957513-c46b7480-5142-11eb-974e-4bf7738cfed0.png">

**Comment by Candlemass** [comment]
That took care of it.

Not sure why would move the dark theme toggle from the settings menu where it was previously but at least now I know.

Thanks.

**Comment by Candlemass** [comment]
That took care of it.

Not sure why they would move the toggle from where it previously was in the settings but now I know.

Thank you.

**Comment by csalmeida** [comment]
Awesome! In that case I'll close the issue.
